elementCouplings_[ 0 ] = std::make_pair(0,0);//(phi,phi)
elementCouplings_[ 1 ] = std::make_pair(0,1);//(phi,tau)
elementCouplings_[ 2 ] = std::make_pair(1,0);//(tau,phi)
elementCouplings_[ 3 ] = std::make_pair(1,1);//(tau,tau)
elementCouplings_[ 4 ] = std::make_pair(1,2);//(tau,sigmax)
elementCouplings_[ 5 ] = std::make_pair(2,0);//(sigmax,phi)
elementCouplings_[ 6 ] = std::make_pair(2,2);//(sigmax,sigmax)
