elementCouplings_.push_back( std::make_pair(0,0));//(phi,phi)
elementCouplings_.push_back( std::make_pair(0,1));//(phi,tau)
elementCouplings_.push_back( std::make_pair(1,0));//(tau,phi)
elementCouplings_.push_back( std::make_pair(1,1));//(tau,tau)
elementCouplings_.push_back( std::make_pair(1,2));//(tau,sigmax)
elementCouplings_.push_back( std::make_pair(2,0));//(sigmax,phi)
elementCouplings_.push_back( std::make_pair(2,2));//(sigmax,sigmax)
