elementCouplings_[ 0 ] = std::make_pair(0,0);//(rho,rho)
elementCouplings_[ 1 ] = std::make_pair(0,1);//(rho,v)
elementCouplings_[ 2 ] = std::make_pair(1,0);//(v,rho)
elementCouplings_[ 3 ] = std::make_pair(1,1);//(v,v)
elementCouplings_[ 4 ] = std::make_pair(1,2);//(v,mu)
elementCouplings_[ 5 ] = std::make_pair(2,0);//(mu,rho)
elementCouplings_[ 6 ] = std::make_pair(2,1);//(mu,v)
elementCouplings_[ 7 ] = std::make_pair(2,2);//(mu,mu)
