intersectionCouplings_[ 0 ] = std::make_pair(0,0);//(rho,rho)
intersectionCouplings_[ 1 ] = std::make_pair(0,1);//(rho,v)
intersectionCouplings_[ 2 ] = std::make_pair(0,2);//(rho,mu)
intersectionCouplings_[ 3 ] = std::make_pair(1,0);//(v,rho)
intersectionCouplings_[ 4 ] = std::make_pair(1,1);//(v,v)
intersectionCouplings_[ 5 ] = std::make_pair(1,2);//(v,mu)
